lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: true
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: false
